#! /bin/bash

source $(dirname $0)/../comun.sh
DESTALT="${COPIA_ACTUAL}/paquetes/"

mkdir -p "$DESTALT"

# debian et al
if which dpkg > /dev/null; then
    DEST=/var/backups/dpkg-get-selections
    dpkg --get-selections "*" > $DESTALT/dpkg-get-selections
    dpkg --get-selections "*" > $DEST
fi

# centos et al
if which rpm > /dev/null; then
    rpm -qa > $DESTALT/rpm_qa
fi
